---
openapi: 3.0.0
info:
   version: 1.3.0
   title: templateaccouting open api specification
   description: screens API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8017
     description: screens
tags:
- name: adds
paths:
   "/adds":
      post:
         tags:
         -  adds
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/adds"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
   "/adds/userid/created_by":
      get:
         tags:
         -  adds
         description: GpGetNounCreatedBy
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      adds:
         type: object
         properties:
            name:
               type: "string"
               description: Description